
package menuutama;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author NaufalSholahuddin
 */
public class DataLayananInternet extends javax.swing.JPanel {
    //koneksi mysql 
    private Connection conn = new Koneksi().connect();
    private DialogTambahData dialog = new DialogTambahData(null, true);
    public DefaultTableModel tabmode;
    private String noId;
    
    /**
     * Creates new form NewJPanel
     */
    public DataLayananInternet() {
        initComponents();
        updateDataTabel();
    }
    
    /**
     * mendapatkan Data Tabel dari database
     */
   protected void updateDataTabel() {

    Object[] Baris = {
        "No.ID",
        "Nama Layanan",
        "Keterangan",
        "Fiber",
        "Harga",
        "FUP",
        "Bandwidth",
        "Layanan Tambahan"
    };

    tabmode = new DefaultTableModel(null, Baris);
    tabelLayananInternet.setModel(tabmode);

    String sql = "SELECT * FROM layanan_internet ORDER BY no_id";

    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);

        while (hasil.next()) {
            String a = hasil.getString("no_id");
            String b = hasil.getString("nama_layanan");
            String c = hasil.getString("keterangan");
            String d = hasil.getString("fiber");
            String e = hasil.getString("harga");
            String f = hasil.getString("fup");
            String g = hasil.getString("bandwidth");
            String h = hasil.getString("layanan_tambahan");

            String[] data = {a, b, c, d, e, f, g, h};
            tabmode.addRow(data);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}


/**
 * Mendapatkan Data dari Tabel
 */
String namaLayanan;   // global (di class utama)

private void getDataTabel() {
    int bar = tabelLayananInternet.getSelectedRow();

    String a = tabmode.getValueAt(bar, 0).toString(); // no_id (opsional)
    String b = tabmode.getValueAt(bar, 1).toString(); // nama_layanan
    String c = tabmode.getValueAt(bar, 2).toString(); // keterangan
    String d = tabmode.getValueAt(bar, 3).toString(); // fiber
    String e = tabmode.getValueAt(bar, 4).toString(); // harga
    String f = tabmode.getValueAt(bar, 5).toString(); // fup
    String g = tabmode.getValueAt(bar, 6).toString(); // bandwidth
    String h = tabmode.getValueAt(bar, 7).toString(); // layanan_tambahan

    // simpan key untuk hapus (berdasarkan nama)
    namaLayanan = b;

    // kalau kamu masih butuh id untuk hal lain (optional)
    noId = a;

    // kirim ke dialog (tanpa no_hp, alamat, dll)
    dialog.setDataTabel(b, c, d, e, f, g, h);
}

protected void hapusDataLayananInternet() {
    if (namaLayanan != null) {

        int ok = JOptionPane.showConfirmDialog(
                null,
                "Apakah data layanan internet ini akan dihapus?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (ok == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM layanan_internet WHERE nama_layanan=?";

            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, namaLayanan);
                stat.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                updateDataTabel();
                namaLayanan = null;

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus : " + e.getMessage());
            }
        }

    } else {
        JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus!");
    }
}



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelLayananInternet = new javax.swing.JTable();
        tombolTambah = new javax.swing.JButton();
        tombolEdit = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        catatan = new javax.swing.JLabel();

        judul.setBackground(new java.awt.Color(255, 255, 255));
        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setForeground(new java.awt.Color(0, 204, 0));
        judul.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judul.setText("  Data Layanan Internet");
        judul.setToolTipText("");
        judul.setOpaque(true);

        Panel.setBackground(new java.awt.Color(255, 255, 255));

        tabelLayananInternet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelLayananInternet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelLayananInternetMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelLayananInternet);

        tombolTambah.setBackground(new java.awt.Color(0, 204, 0));
        tombolTambah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tombolTambah.setForeground(new java.awt.Color(255, 255, 255));
        tombolTambah.setText("Tambah Data Layanan Internet");
        tombolTambah.setBorder(null);
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolEdit.setBackground(new java.awt.Color(204, 255, 0));
        tombolEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tombolEdit.setForeground(new java.awt.Color(255, 255, 255));
        tombolEdit.setText("Edit");
        tombolEdit.setBorder(null);
        tombolEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolEditActionPerformed(evt);
            }
        });

        tombolHapus.setBackground(new java.awt.Color(102, 0, 0));
        tombolHapus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tombolHapus.setForeground(new java.awt.Color(255, 255, 255));
        tombolHapus.setText("Hapus");
        tombolHapus.setBorder(null);
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        catatan.setText("Catatan : Edit/Hapus data layanan Internet, klik data pada tabel terlebih dahulu");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap(560, Short.MAX_VALUE)
                .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelLayout.createSequentialGroup()
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(catatan)
                                .addGroup(PanelLayout.createSequentialGroup()
                                    .addGap(439, 439, 439)
                                    .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(tombolHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 44, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tombolTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelLayout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(catatan)
                    .addGap(18, 18, 18)
                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tombolHapus, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addComponent(tombolEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                    .addGap(0, 45, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(239, 239, 239))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
          hapusDataLayananInternet();
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEditActionPerformed
        // TODO add your handling code here:
        if(noId != null){
            dialog.show();
            updateDataTabel();
            noId=null;
        }else{
            JOptionPane.showMessageDialog(null, "Pilih data yang ingin diUbah! ");
        }
    }//GEN-LAST:event_tombolEditActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        // TODO add your handling code here:
            dialog.kosong();
            dialog.show();
            updateDataTabel();  
            noId=null;
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void tabelLayananInternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelLayananInternetMouseClicked
        // TODO add your handling code here:
        getDataTabel();
    }//GEN-LAST:event_tabelLayananInternetMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel catatan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JTable tabelLayananInternet;
    private javax.swing.JButton tombolEdit;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolTambah;
    // End of variables declaration//GEN-END:variables
}
