
package menuutama;
import LoginAdmin.Login;
import LoginAdmin.Login;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Cursor;
import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import koneksi.Koneksi;
import com.itextpdf.text.BaseColor;
import java.sql.*;
import java.awt.Frame;
import javax.swing.table.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfGState;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPageEventHelper;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.LineSeparator;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.UUID;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.SwingUtilities;
import javax.swing.Timer;


/**
 *
 * @author NaufalSholahuddin
 */
public class MenuUtama extends javax.swing.JFrame {
    Color hoverButton;
    private Connection conn = (Connection) new Koneksi().connect();
    
    /**
     * Creates new form NewJFrame
     */
    public MenuUtama() {
        initComponents();
        setVisible(true);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        sliderMenuDefault();
        this.hoverButton = calonPelamar.getBackground();
        Pane.add(Home);
        Pane.repaint();
        Pane.revalidate();
    }
    // untuk sliderMenu
    private void sliderMenuDefault(){
        slideMenuLaporan.setVisible(false);
        slideMenuPengaturan.setVisible(false);
    }
    
    private void hiddenSubMenu(){
        if(slideMenuLaporan.isVisible() == true){
            slideMenuLaporan.setVisible(false);
            slideMenuPengaturan.setVisible(false);
        }
        if(slideMenuPengaturan.isVisible() == true){
            slideMenuLaporan.setVisible(false);
            slideMenuPengaturan.setVisible(false);
        }
    }
    
    private void showSubMenu(JPanel subMenu){
        if(subMenu.isVisible() == false){
            hiddenSubMenu();
            subMenu.setVisible(true);
        }else{
            subMenu.setVisible(false);
        }
    }
    
    // ================== GLOBAL (di luar method / di dalam class) ==================
private static final String LOGO_PATH =
        "C:\\Users\\ASUS\\Documents\\NetBeansProjects\\spk_pemilihan_layanan_internet\\src\\image\\logo.png";

private static final String NAMA_INSTANSI = "PT.Omega Media Global";

private static final String ALAMAT_INSTANSI =
        "JL. Mayor Oking Jaya Atmaja No. 89, Ciriung, Kec. Cibinong"
      + "Kab. Bogor, Prov. Jawa Barat 16918";

private static final String LOKASI_TTD = "Cibinong";
private static final String JABATAN_TTD = "Manager PT. Omega Media Global";
private static final String NAMA_TTD = "Admin";

    //akhis slider menu
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        calonPelamar = new javax.swing.JLabel();
        kriteria = new javax.swing.JLabel();
        slideMenuLaporan = new javax.swing.JPanel();
        laporanCalonPelamar = new javax.swing.JLabel();
        laporanPrioritasKriteria = new javax.swing.JLabel();
        laporanPrioritasSubKriteria = new javax.swing.JLabel();
        laporanHasilSeleksi = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        slideMenuPengaturan = new javax.swing.JPanel();
        menuPengaturanKriteria = new javax.swing.JLabel();
        menuPengaturanSubKriteria = new javax.swing.JLabel();
        seleksi = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        Pane = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();

        Home.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang, di Aplikasi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistem Pendukung Keputusan Pemilihan Layanan Internet");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PT OMEGA MEDIA GLOBAL Menggunakan Metode AHP");

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(0, 0, 51));
        Menu.setMaximumSize(new java.awt.Dimension(32767, 600));

        calonPelamar.setBackground(new java.awt.Color(0, 0, 51));
        calonPelamar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calonPelamar.setForeground(new java.awt.Color(255, 255, 255));
        calonPelamar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calonPelamar.setText("       Data Layanan Internet");
        calonPelamar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        calonPelamar.setOpaque(true);
        calonPelamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calonPelamarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calonPelamarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calonPelamarMouseExited(evt);
            }
        });

        kriteria.setBackground(new java.awt.Color(0, 0, 51));
        kriteria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kriteria.setForeground(new java.awt.Color(255, 255, 255));
        kriteria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kriteria.setText("Kriteria");
        kriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kriteria.setOpaque(true);
        kriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kriteriaMouseExited(evt);
            }
        });

        slideMenuLaporan.setBackground(new java.awt.Color(0, 0, 51));
        slideMenuLaporan.setForeground(new java.awt.Color(255, 255, 255));

        laporanCalonPelamar.setBackground(new java.awt.Color(255, 255, 255));
        laporanCalonPelamar.setText("    Laporan Layanan Internet");
        laporanCalonPelamar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanCalonPelamar.setOpaque(true);
        laporanCalonPelamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanCalonPelamarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanCalonPelamarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanCalonPelamarMouseExited(evt);
            }
        });

        laporanPrioritasKriteria.setBackground(new java.awt.Color(255, 255, 255));
        laporanPrioritasKriteria.setText("    Laporan Prioritas Kriteria");
        laporanPrioritasKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanPrioritasKriteria.setOpaque(true);
        laporanPrioritasKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanPrioritasKriteriaMouseExited(evt);
            }
        });

        laporanPrioritasSubKriteria.setBackground(new java.awt.Color(255, 255, 255));
        laporanPrioritasSubKriteria.setText("    Laporan Prioritas SubKriteria");
        laporanPrioritasSubKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanPrioritasSubKriteria.setOpaque(true);
        laporanPrioritasSubKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanPrioritasSubKriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanPrioritasSubKriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanPrioritasSubKriteriaMouseExited(evt);
            }
        });

        laporanHasilSeleksi.setBackground(new java.awt.Color(255, 255, 255));
        laporanHasilSeleksi.setText("    Laporan Hasil Akhir");
        laporanHasilSeleksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        laporanHasilSeleksi.setOpaque(true);
        laporanHasilSeleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanHasilSeleksiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuLaporanLayout = new javax.swing.GroupLayout(slideMenuLaporan);
        slideMenuLaporan.setLayout(slideMenuLaporanLayout);
        slideMenuLaporanLayout.setHorizontalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(laporanCalonPelamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanPrioritasKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanPrioritasSubKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(laporanHasilSeleksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slideMenuLaporanLayout.setVerticalGroup(
            slideMenuLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideMenuLaporanLayout.createSequentialGroup()
                .addComponent(laporanCalonPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanPrioritasKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanPrioritasSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporanHasilSeleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        laporan.setBackground(new java.awt.Color(0, 0, 51));
        laporan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laporan.setForeground(new java.awt.Color(255, 255, 255));
        laporan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laporan.setText("  Cetak Laporan");
        laporan.setOpaque(true);
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporanMouseExited(evt);
            }
        });

        slideMenuPengaturan.setBackground(new java.awt.Color(0, 0, 51));
        slideMenuPengaturan.setForeground(new java.awt.Color(255, 255, 255));

        menuPengaturanKriteria.setBackground(new java.awt.Color(255, 255, 255));
        menuPengaturanKriteria.setText(" Pengaturan Prioritas Kriteria");
        menuPengaturanKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPengaturanKriteria.setOpaque(true);
        menuPengaturanKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPengaturanKriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPengaturanKriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPengaturanKriteriaMouseExited(evt);
            }
        });

        menuPengaturanSubKriteria.setBackground(new java.awt.Color(255, 255, 255));
        menuPengaturanSubKriteria.setText(" Pengaturan Prioritas SubKriteria");
        menuPengaturanSubKriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPengaturanSubKriteria.setOpaque(true);
        menuPengaturanSubKriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPengaturanSubKriteriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuPengaturanSubKriteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuPengaturanSubKriteriaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout slideMenuPengaturanLayout = new javax.swing.GroupLayout(slideMenuPengaturan);
        slideMenuPengaturan.setLayout(slideMenuPengaturanLayout);
        slideMenuPengaturanLayout.setHorizontalGroup(
            slideMenuPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPengaturanKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuPengaturanSubKriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        slideMenuPengaturanLayout.setVerticalGroup(
            slideMenuPengaturanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideMenuPengaturanLayout.createSequentialGroup()
                .addComponent(menuPengaturanKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuPengaturanSubKriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        seleksi.setBackground(new java.awt.Color(0, 0, 51));
        seleksi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        seleksi.setForeground(new java.awt.Color(255, 255, 255));
        seleksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleksi.setText("Seleksi");
        seleksi.setOpaque(true);
        seleksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seleksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seleksiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calonPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(slideMenuPengaturan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(seleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(slideMenuLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calonPelamar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(slideMenuPengaturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(seleksi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(slideMenuLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        judul1.setBackground(new java.awt.Color(255, 255, 255));
        judul1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        judul1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        judul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        judul1.setText("SPK Pemilihan Layanan Internet PT OMEGA MEDIA GLOBAL");
        judul1.setOpaque(true);
        jPanel5.add(judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1337, 117));

        Pane.setBackground(new java.awt.Color(255, 255, 255));
        Pane.setMaximumSize(new java.awt.Dimension(1200, 650));
        Pane.setMinimumSize(new java.awt.Dimension(380, 200));
        Pane.setPreferredSize(new java.awt.Dimension(600, 570));
        Pane.setLayout(new java.awt.CardLayout());
        jPanel5.add(Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 123, 1133, -1));

        logout.setBackground(new java.awt.Color(204, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("  Log Out");
        logout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logout.setOpaque(true);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel5.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 192, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setBackground(Color.BLACK);
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setBackground(new Color(51,51,51));
        logout.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void seleksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseExited
        // TODO add your handling code here:
        seleksi.setBackground(hoverButton);
    }//GEN-LAST:event_seleksiMouseExited

    private void seleksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseEntered
        // TODO add your handling code here:
        seleksi.setBackground(new Color(51,51,51));
        seleksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_seleksiMouseEntered

    private void seleksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleksiMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel
        Pane.add(new Seleksi());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_seleksiMouseClicked

    private void menuPengaturanSubKriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPengaturanSubKriteriaMouseExited

    }//GEN-LAST:event_menuPengaturanSubKriteriaMouseExited

    private void menuPengaturanSubKriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPengaturanSubKriteriaMouseEntered
        menuPengaturanSubKriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuPengaturanSubKriteriaMouseEntered

    private void menuPengaturanSubKriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPengaturanSubKriteriaMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel 
        Pane.add(new PengaturanSubKriteria());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuPengaturanSubKriteriaMouseClicked

    private void menuPengaturanKriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPengaturanKriteriaMouseExited
     
    }//GEN-LAST:event_menuPengaturanKriteriaMouseExited

    private void menuPengaturanKriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPengaturanKriteriaMouseEntered
  
        menuPengaturanKriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_menuPengaturanKriteriaMouseEntered

    private void menuPengaturanKriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPengaturanKriteriaMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel
        Pane.add(new PengaturanKriteria());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_menuPengaturanKriteriaMouseClicked

    private void laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseExited
        // TODO add your handling code here:
        laporan.setBackground(hoverButton);
    }//GEN-LAST:event_laporanMouseExited

    private void laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseEntered
        // TODO add your handling code here:
        laporan.setBackground(new Color(51,51,51));
        laporan.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanMouseEntered

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        // TODO add your handling code here:
        showSubMenu(slideMenuLaporan);
    }//GEN-LAST:event_laporanMouseClicked

    private void laporanHasilSeleksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseExited

    }//GEN-LAST:event_laporanHasilSeleksiMouseExited

    private void laporanHasilSeleksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseEntered

        laporanHasilSeleksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanHasilSeleksiMouseEntered
private void generatePDFLaporanRanking() {
    String fileName = null;

    try {
        // ================== QUERY (JOIN SELEKSI + LAYANAN INTERNET) ==================
        String query =
                "SELECT s.no_id, l.nama_layanan, l.fiber, l.harga, l.fup, l.bandwidth, l.layanan_tambahan, s.hasil_penilaian " +
                "FROM seleksi s " +
                "JOIN layanan_internet l ON s.no_id = l.no_id " +
                "ORDER BY s.hasil_penilaian DESC";

        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        Document document = new Document();

        // ================== FILE OUTPUT ==================
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");
        LocalDateTime currentDateTime = LocalDateTime.now();
        String currentTimeStamp = currentDateTime.format(formatter);
        fileName = "C:\\Users\\ASUS\\Desktop\\laporan_ranking_layanan_internet_" + currentTimeStamp + ".pdf";

        PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();

        // ================== HEADER ==================
        PdfPTable headerTable = new PdfPTable(2);
        headerTable.setWidthPercentage(100);
        headerTable.setWidths(new float[]{1.5f, 6f});

        // Logo kiri
        Image logo = Image.getInstance(LOGO_PATH);
        logo.scaleToFit(80, 80);

        PdfPCell logoCell = new PdfPCell(logo);
        logoCell.setBorder(Rectangle.NO_BORDER);
        logoCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        logoCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        headerTable.addCell(logoCell);

        // Teks kanan
        Font fontHeader = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
        Font fontAlamat = new Font(Font.FontFamily.TIMES_ROMAN, 9, Font.NORMAL);

        Paragraph namaInstansi = new Paragraph(NAMA_INSTANSI, fontHeader);
        namaInstansi.setAlignment(Element.ALIGN_CENTER);

        Paragraph alamatInstansi = new Paragraph(ALAMAT_INSTANSI, fontAlamat);
        alamatInstansi.setAlignment(Element.ALIGN_CENTER);

        PdfPCell textCell = new PdfPCell();
        textCell.setBorder(Rectangle.NO_BORDER);
        textCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        textCell.addElement(namaInstansi);
        textCell.addElement(alamatInstansi);

        headerTable.addCell(textCell);

        document.add(headerTable);

        // Garis pembatas
        document.add(new Paragraph("\n"));
        LineSeparator line = new LineSeparator();
        line.setLineColor(BaseColor.BLACK);
        line.setLineWidth(1);
        document.add(line);
        document.add(new Paragraph("\n"));

        // ================== JUDUL ==================
        Paragraph judul = new Paragraph(
                "LAPORAN HASIL AKHIR PERANGKINGAN AHP LAYANAN INTERNET",
                new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD)
        );
        judul.setAlignment(Element.ALIGN_CENTER);
        document.add(judul);
        document.add(new Paragraph("\n"));

        // ================== TABLE ==================
        // 9 kolom
        PdfPTable table = new PdfPTable(9);
        table.getDefaultCell().setBorder(Rectangle.BOTTOM);

        Font smallFont = new Font(Font.FontFamily.TIMES_ROMAN, 8, Font.NORMAL);

        String[] kolom = {
                "Ranking",
                "ID",
                "Nama Layanan",
                "Fiber",
                "Harga",
                "FUP",
                "Bandwidth",
                "Layanan Tambahan",
                "Hasil Penilaian"
        };

        for (String column : kolom) {
            PdfPCell cell = new PdfPCell(new Phrase(column, smallFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBorder(Rectangle.BOX);
            table.addCell(cell);
        }

        int rank = 1;
        while (rs.next()) {

            PdfPCell cellRanking = new PdfPCell(new Phrase(Integer.toString(rank), smallFont));
            cellRanking.setBorder(Rectangle.BOX);
            cellRanking.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellRanking);

            String idVal = rs.getString("no_id");
            if (idVal == null || idVal.trim().isEmpty()) idVal = "-";
            PdfPCell cellId = new PdfPCell(new Phrase(idVal, smallFont));
            cellId.setBorder(Rectangle.BOX);
            cellId.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellId);

            String namaVal = rs.getString("nama_layanan");
            if (namaVal == null || namaVal.trim().isEmpty()) namaVal = "-";
            PdfPCell cellNama = new PdfPCell(new Phrase(namaVal, smallFont));
            cellNama.setBorder(Rectangle.BOX);
            table.addCell(cellNama);

            String fiberVal = rs.getString("fiber");
            if (fiberVal == null || fiberVal.trim().isEmpty()) fiberVal = "-";
            PdfPCell cellFiber = new PdfPCell(new Phrase(fiberVal, smallFont));
            cellFiber.setBorder(Rectangle.BOX);
            cellFiber.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellFiber);

            String hargaVal = rs.getString("harga");
            if (hargaVal == null || hargaVal.trim().isEmpty()) hargaVal = "-";
            PdfPCell cellHarga = new PdfPCell(new Phrase(hargaVal, smallFont));
            cellHarga.setBorder(Rectangle.BOX);
            cellHarga.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellHarga);

            String fupVal = rs.getString("fup");
            if (fupVal == null || fupVal.trim().isEmpty()) fupVal = "-";
            PdfPCell cellFUP = new PdfPCell(new Phrase(fupVal, smallFont));
            cellFUP.setBorder(Rectangle.BOX);
            cellFUP.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellFUP);

            String bwVal = rs.getString("bandwidth");
            if (bwVal == null || bwVal.trim().isEmpty()) bwVal = "-";
            PdfPCell cellBW = new PdfPCell(new Phrase(bwVal, smallFont));
            cellBW.setBorder(Rectangle.BOX);
            cellBW.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellBW);

            String layananVal = rs.getString("layanan_tambahan");
            if (layananVal == null || layananVal.trim().isEmpty()) layananVal = "-";
            PdfPCell cellLayanan = new PdfPCell(new Phrase(layananVal, smallFont));
            cellLayanan.setBorder(Rectangle.BOX);
            table.addCell(cellLayanan);

            String nilai = rs.getString("hasil_penilaian");
            if (nilai == null || nilai.trim().isEmpty()) nilai = "-";
            PdfPCell cellHasil = new PdfPCell(new Phrase(nilai, smallFont));
            cellHasil.setBorder(Rectangle.BOX);
            cellHasil.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellHasil);

            rank++;
        }

        // Lebar kolom biar rapi
        float[] columnWidths = {1.2f, 1.3f, 3.0f, 1.6f, 2.0f, 1.3f, 1.6f, 4.0f, 1.6f};
        table.setTotalWidth(document.getPageSize().getWidth() - document.leftMargin() - document.rightMargin());
        table.setLockedWidth(true);
        table.setWidths(columnWidths);

        document.add(table);

        // ================== INFO TEXT ==================
        Paragraph infoText = new Paragraph(
                "Data di atas merupakan hasil akhir perangkingan layanan internet berdasarkan perhitungan AHP. " +
                "Alternatif dengan nilai tertinggi menjadi rekomendasi utama karena paling sesuai dengan kriteria yang digunakan.",
                new Font(Font.FontFamily.TIMES_ROMAN, 10, Font.NORMAL)
        );
        infoText.setAlignment(Element.ALIGN_JUSTIFIED);
        infoText.setSpacingBefore(20);
        infoText.setSpacingAfter(20);
        document.add(infoText);

        // ================== TTD ==================
        DateTimeFormatter dateFormatter =
                DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy", new Locale("id", "ID"));
        String currentDate = LocalDate.now().format(dateFormatter);

        String formattedDate = LOKASI_TTD + ", " + currentDate;

        Paragraph dateTimeParagraph = new Paragraph(
                formattedDate,
                new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.ITALIC)
        );
        dateTimeParagraph.setAlignment(Element.ALIGN_RIGHT);
        dateTimeParagraph.setSpacingBefore(20);
        document.add(dateTimeParagraph);

        Paragraph jabatan = new Paragraph(JABATAN_TTD, new Font(Font.FontFamily.TIMES_ROMAN, 12));
        jabatan.setAlignment(Element.ALIGN_RIGHT);
        document.add(jabatan);

        document.add(new Paragraph("\n\n\n\n"));

        Paragraph namaPejabat = new Paragraph(NAMA_TTD, new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD));
        namaPejabat.setAlignment(Element.ALIGN_RIGHT);
        document.add(namaPejabat);

        // ================== CLOSE ==================
        document.close();

        final String finalFileName = fileName;

        SwingUtilities.invokeLater(() -> {
            JPanel loadingPanel = new JPanel();
            JProgressBar progressBar = new JProgressBar();
            progressBar.setIndeterminate(true);
            loadingPanel.add(progressBar);

            JOptionPane optionPane = new JOptionPane(
                    loadingPanel,
                    JOptionPane.INFORMATION_MESSAGE,
                    JOptionPane.DEFAULT_OPTION,
                    null,
                    new Object[]{},
                    null
            );
            JDialog dialog = optionPane.createDialog("Generate Laporan Ranking Layanan Internet");

            Timer timer = new Timer(2000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    dialog.dispose();
                    JOptionPane.showMessageDialog(null, "Data berhasil digenerate. Tekan OK untuk membuka file.");
                    try {
                        File file = new File(finalFileName);
                        Desktop.getDesktop().open(file);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            });
            timer.setRepeats(false);
            timer.start();

            dialog.setVisible(true);
        });

    } catch (SQLException | DocumentException | IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal generate PDF: " + ex.getMessage());
    }
}



    private void laporanHasilSeleksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanHasilSeleksiMouseClicked
generatePDFLaporanRanking();
    }//GEN-LAST:event_laporanHasilSeleksiMouseClicked

    private void laporanPrioritasSubKriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasSubKriteriaMouseExited
     
    }//GEN-LAST:event_laporanPrioritasSubKriteriaMouseExited

    private void laporanPrioritasSubKriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasSubKriteriaMouseEntered

        laporanPrioritasSubKriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanPrioritasSubKriteriaMouseEntered
private void generatePDFLaporanSubKriteria() {
    String fileName = null;

    try {
        // ✅ Pakai conn global (tidak bikin koneksi baru)
        String query = "SELECT kd_kriteria, nama_kriteria, nama_sub_kriteria, prioritas_kepentingan " +
                       "FROM sub_kriteria ORDER BY kd_kriteria, no_sub";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        Document document = new Document();

        // ✅ file output (lokal di method)
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");
        LocalDateTime currentDateTime = LocalDateTime.now();
        String currentTimeStamp = currentDateTime.format(formatter);
        fileName = "C:\\Users\\ASUS\\Desktop\\laporan_sub_kriteria_" + currentTimeStamp + ".pdf";

        PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();

        // ================== HEADER (FIXED: tidak nabrak) ==================
        PdfPTable headerTable = new PdfPTable(2);
        headerTable.setWidthPercentage(100);
        headerTable.setWidths(new float[]{1.5f, 6f});

        // Logo kiri
        Image logo = Image.getInstance(LOGO_PATH);
        logo.scaleToFit(80, 80);

        PdfPCell logoCell = new PdfPCell(logo);
        logoCell.setBorder(Rectangle.NO_BORDER);
        logoCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        logoCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        headerTable.addCell(logoCell);

        // Teks kanan
        Font fontHeader = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
        Font fontAlamat = new Font(Font.FontFamily.TIMES_ROMAN, 9, Font.NORMAL);

        Paragraph namaInstansi = new Paragraph(NAMA_INSTANSI, fontHeader);
        namaInstansi.setAlignment(Element.ALIGN_CENTER);

        Paragraph alamatInstansi = new Paragraph(ALAMAT_INSTANSI, fontAlamat);
        alamatInstansi.setAlignment(Element.ALIGN_CENTER);

        PdfPCell textCell = new PdfPCell();
        textCell.setBorder(Rectangle.NO_BORDER);
        textCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        textCell.addElement(namaInstansi);
        textCell.addElement(alamatInstansi);

        headerTable.addCell(textCell);

        document.add(headerTable);

        // Garis pembatas
        document.add(new Paragraph("\n"));
        LineSeparator line = new LineSeparator();
        line.setLineColor(BaseColor.BLACK);
        line.setLineWidth(1);
        document.add(line);
        document.add(new Paragraph("\n"));

        // ================== JUDUL ==================
        Paragraph judul = new Paragraph(
                "DATA SUB-KRITERIA PENERIMA BANTUAN SOSIAL",
                new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD)
        );
        judul.setAlignment(Element.ALIGN_CENTER);
        document.add(judul);
        document.add(new Paragraph("\n"));

        // ================== TABLE ==================
        PdfPTable table = new PdfPTable(4);
        table.getDefaultCell().setBorder(Rectangle.BOTTOM);

        Font smallFont = new Font(Font.FontFamily.TIMES_ROMAN, 8, Font.NORMAL);

        String[] kolom = {"Kode Kriteria", "Nama Kriteria", "Nama SubKriteria", "Kepentingan SubKriteria"};
        for (String column : kolom) {
            PdfPCell cell = new PdfPCell(new Phrase(column, smallFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBorder(Rectangle.BOX);
            table.addCell(cell);
        }

        while (rs.next()) {
            PdfPCell cellKodeKriteria = new PdfPCell(new Phrase(rs.getString("kd_kriteria"), smallFont));
            cellKodeKriteria.setBorder(Rectangle.BOX);
            table.addCell(cellKodeKriteria);

            PdfPCell cellNamaKriteria = new PdfPCell(new Phrase(rs.getString("nama_kriteria"), smallFont));
            cellNamaKriteria.setBorder(Rectangle.BOX);
            table.addCell(cellNamaKriteria);

            PdfPCell cellNamaSubKriteria = new PdfPCell(new Phrase(rs.getString("nama_sub_kriteria"), smallFont));
            cellNamaSubKriteria.setBorder(Rectangle.BOX);
            table.addCell(cellNamaSubKriteria);

            PdfPCell cellPrioritas = new PdfPCell(new Phrase(rs.getString("prioritas_kepentingan"), smallFont));
            cellPrioritas.setBorder(Rectangle.BOX);
            table.addCell(cellPrioritas);
        }

        float[] columnWidths = {2, 4, 4, 4};
        table.setTotalWidth(document.getPageSize().getWidth() - document.leftMargin() - document.rightMargin());
        table.setLockedWidth(true);
        table.setWidths(columnWidths);

        document.add(table);

        // ================== TTD ==================
        DateTimeFormatter dateFormatter =
                DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy", new Locale("id", "ID"));
        String currentDate = LocalDate.now().format(dateFormatter);

        String formattedDate = LOKASI_TTD + ", " + currentDate;

        Paragraph dateTimeParagraph = new Paragraph(
                formattedDate,
                new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.ITALIC)
        );
        dateTimeParagraph.setAlignment(Element.ALIGN_RIGHT);
        dateTimeParagraph.setSpacingBefore(20);
        document.add(dateTimeParagraph);

        Paragraph jabatan = new Paragraph(JABATAN_TTD, new Font(Font.FontFamily.TIMES_ROMAN, 12));
        jabatan.setAlignment(Element.ALIGN_RIGHT);
        document.add(jabatan);

        document.add(new Paragraph("\n\n\n\n"));

        Paragraph namaPejabat = new Paragraph(NAMA_TTD, new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD));
        namaPejabat.setAlignment(Element.ALIGN_RIGHT);
        document.add(namaPejabat);

        // ================== CLOSE ==================
        document.close();
        // ✅ conn global: jangan ditutup di sini kalau masih dipakai fitur lain
        // conn.close();

        final String finalFileName = fileName;

        SwingUtilities.invokeLater(() -> {
            JPanel loadingPanel = new JPanel();
            JProgressBar progressBar = new JProgressBar();
            progressBar.setIndeterminate(true);
            loadingPanel.add(progressBar);

            JOptionPane optionPane = new JOptionPane(
                    loadingPanel,
                    JOptionPane.INFORMATION_MESSAGE,
                    JOptionPane.DEFAULT_OPTION,
                    null,
                    new Object[]{},
                    null
            );
            JDialog dialog = optionPane.createDialog("Generate Laporan Sub-Kriteria");

            Timer timer = new Timer(2000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    dialog.dispose();
                    JOptionPane.showMessageDialog(null, "Data berhasil digenerate. Tekan OK untuk membuka file.");
                    try {
                        File file = new File(finalFileName);
                        Desktop.getDesktop().open(file);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            });
            timer.setRepeats(false);
            timer.start();

            dialog.setVisible(true);
        });

    } catch (SQLException | DocumentException | IOException ex) {
        ex.printStackTrace();
    }
}


    private void laporanPrioritasSubKriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasSubKriteriaMouseClicked
generatePDFLaporanSubKriteria();
    }//GEN-LAST:event_laporanPrioritasSubKriteriaMouseClicked

    private void laporanPrioritasKriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasKriteriaMouseExited
   
    }//GEN-LAST:event_laporanPrioritasKriteriaMouseExited

    private void laporanPrioritasKriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasKriteriaMouseEntered
 
        laporanPrioritasKriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanPrioritasKriteriaMouseEntered
private void generatePDFLaporanKriteria() {
    String fileName = null;

    try {
        // ✅ Pakai conn global (tidak bikin koneksi baru)
        String query = "SELECT kd_kriteria, nama_kriteria, prioritas_kepentingan FROM kriteria ORDER BY kd_kriteria";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        Document document = new Document();

        // ✅ File output (tetap lokal di method)
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");
        LocalDateTime currentDateTime = LocalDateTime.now();
        String currentTimeStamp = currentDateTime.format(formatter);
        fileName = "C:\\Users\\ASUS\\Desktop\\laporan_kriteria_" + currentTimeStamp + ".pdf";

        PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();

        // ================== HEADER (FIX: logo tidak nabrak alamat) ==================
        PdfPTable headerTable = new PdfPTable(2);
        headerTable.setWidthPercentage(100);
        headerTable.setWidths(new float[]{1.5f, 6f});

        // Logo kiri
        Image logo = Image.getInstance(LOGO_PATH);
        logo.scaleToFit(80, 80);

        PdfPCell logoCell = new PdfPCell(logo);
        logoCell.setBorder(Rectangle.NO_BORDER);
        logoCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        logoCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        headerTable.addCell(logoCell);

        // Teks kanan (nama instansi + alamat)
        Font fontHeader = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
        Font fontAlamat = new Font(Font.FontFamily.TIMES_ROMAN, 9, Font.NORMAL);

        Paragraph namaInstansi = new Paragraph(NAMA_INSTANSI, fontHeader);
        namaInstansi.setAlignment(Element.ALIGN_CENTER);

        Paragraph alamatInstansi = new Paragraph(ALAMAT_INSTANSI, fontAlamat);
        alamatInstansi.setAlignment(Element.ALIGN_CENTER);

        PdfPCell textCell = new PdfPCell();
        textCell.setBorder(Rectangle.NO_BORDER);
        textCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        textCell.addElement(namaInstansi);
        textCell.addElement(alamatInstansi);
        headerTable.addCell(textCell);

        document.add(headerTable);

        // Garis pembatas
        document.add(new Paragraph("\n"));
        LineSeparator line = new LineSeparator();
        line.setLineColor(BaseColor.BLACK);
        line.setLineWidth(1);
        document.add(line);
        document.add(new Paragraph("\n"));

        // ================== JUDUL ==================
        Paragraph judul = new Paragraph(
                "DATA KRITERIA PENERIMA BANTUAN SOSIAL",
                new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD)
        );
        judul.setAlignment(Element.ALIGN_CENTER);
        document.add(judul);
        document.add(new Paragraph("\n"));

        // ================== TABLE ==================
        PdfPTable table = new PdfPTable(3);
        table.getDefaultCell().setBorder(Rectangle.BOTTOM);

        Font smallFont = new Font(Font.FontFamily.TIMES_ROMAN, 8, Font.NORMAL);

        String[] kolom = {"Kode Kriteria", "Nama Kriteria", "Prioritas Kepentingan"};
        for (String column : kolom) {
            PdfPCell cell = new PdfPCell(new Phrase(column, smallFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBorder(Rectangle.BOX);
            table.addCell(cell);
        }

        while (rs.next()) {
            PdfPCell cellKode = new PdfPCell(new Phrase(rs.getString("kd_kriteria"), smallFont));
            cellKode.setBorder(Rectangle.BOX);
            table.addCell(cellKode);

            PdfPCell cellNama = new PdfPCell(new Phrase(rs.getString("nama_kriteria"), smallFont));
            cellNama.setBorder(Rectangle.BOX);
            table.addCell(cellNama);

            PdfPCell cellPrioritas = new PdfPCell(new Phrase(rs.getString("prioritas_kepentingan"), smallFont));
            cellPrioritas.setBorder(Rectangle.BOX);
            table.addCell(cellPrioritas);
        }

        float[] columnWidths = {2, 4, 4};
        table.setTotalWidth(document.getPageSize().getWidth() - document.leftMargin() - document.rightMargin());
        table.setLockedWidth(true);
        table.setWidths(columnWidths);

        document.add(table);

        // ================== TTD ==================
        DateTimeFormatter dateFormatter =
                DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy", new Locale("id", "ID"));
        String currentDate = LocalDate.now().format(dateFormatter);

        String formattedDate = LOKASI_TTD + ", " + currentDate;

        Paragraph dateTimeParagraph = new Paragraph(
                formattedDate,
                new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.ITALIC)
        );
        dateTimeParagraph.setAlignment(Element.ALIGN_RIGHT);
        dateTimeParagraph.setSpacingBefore(20);
        document.add(dateTimeParagraph);

        Paragraph jabatan = new Paragraph(JABATAN_TTD, new Font(Font.FontFamily.TIMES_ROMAN, 12));
        jabatan.setAlignment(Element.ALIGN_RIGHT);
        document.add(jabatan);

        document.add(new Paragraph("\n\n\n\n"));

        Paragraph namaPejabat = new Paragraph(NAMA_TTD, new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD));
        namaPejabat.setAlignment(Element.ALIGN_RIGHT);
        document.add(namaPejabat);

        // ================== CLOSE ==================
        document.close();
        // ✅ conn global: jangan ditutup di sini kalau masih dipakai di fitur lain
        // conn.close();

        final String finalFileName = fileName;

        SwingUtilities.invokeLater(() -> {
            JPanel loadingPanel = new JPanel();
            JProgressBar progressBar = new JProgressBar();
            progressBar.setIndeterminate(true);
            loadingPanel.add(progressBar);

            JOptionPane optionPane = new JOptionPane(
                    loadingPanel,
                    JOptionPane.INFORMATION_MESSAGE,
                    JOptionPane.DEFAULT_OPTION,
                    null,
                    new Object[]{},
                    null
            );
            JDialog dialog = optionPane.createDialog("Generate Laporan Kriteria");

            Timer timer = new Timer(2000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    dialog.dispose();
                    JOptionPane.showMessageDialog(null, "Data berhasil digenerate. Tekan OK untuk membuka file.");
                    try {
                        File file = new File(finalFileName);
                        Desktop.getDesktop().open(file);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            });
            timer.setRepeats(false);
            timer.start();

            dialog.setVisible(true);
        });

    } catch (SQLException | DocumentException | IOException ex) {
        ex.printStackTrace();
    }
}


    private void laporanPrioritasKriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanPrioritasKriteriaMouseClicked
generatePDFLaporanKriteria();
    }//GEN-LAST:event_laporanPrioritasKriteriaMouseClicked

    private void laporanCalonPelamarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanCalonPelamarMouseExited
        
    }//GEN-LAST:event_laporanCalonPelamarMouseExited

    private void laporanCalonPelamarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanCalonPelamarMouseEntered
  
        laporanCalonPelamar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_laporanCalonPelamarMouseEntered
private void generatePDFLaporanLayananInternet() {
    String fileName = null;

    try {
        // ================== AMBIL DATA (DATA LAYANAN INTERNET) ==================
        String query =
                "SELECT no_id, nama_layanan, keterangan, fiber, harga, fup, bandwidth, layanan_tambahan " +
                "FROM layanan_internet ORDER BY no_id ASC";
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);

        Document document = new Document();

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");
        LocalDateTime currentDateTime = LocalDateTime.now();
        String currentTimeStamp = currentDateTime.format(formatter);

        // ✅ filepath (sesuaikan kalau mau)
        fileName = "C:\\Users\\ASUS\\Desktop\\laporan_layanan_internet_" + currentTimeStamp + ".pdf";

        PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();

        // ================== HEADER (FIXED) ==================
        PdfPTable headerTable = new PdfPTable(2);
        headerTable.setWidthPercentage(100);
        headerTable.setWidths(new float[]{1.5f, 6});

        // ===== LOGO =====
        Image logo = Image.getInstance(LOGO_PATH);
        logo.scaleToFit(80, 80);

        PdfPCell logoCell = new PdfPCell(logo);
        logoCell.setBorder(Rectangle.NO_BORDER);
        logoCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        logoCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        headerTable.addCell(logoCell);

        // ===== TEXT HEADER =====
        Font fontHeader = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
        Font fontAlamat = new Font(Font.FontFamily.TIMES_ROMAN, 9, Font.NORMAL);

        Paragraph namaInstansi = new Paragraph(NAMA_INSTANSI, fontHeader);
        namaInstansi.setAlignment(Element.ALIGN_CENTER);

        Paragraph alamatInstansi = new Paragraph(ALAMAT_INSTANSI, fontAlamat);
        alamatInstansi.setAlignment(Element.ALIGN_CENTER);

        PdfPCell textCell = new PdfPCell();
        textCell.setBorder(Rectangle.NO_BORDER);
        textCell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        textCell.addElement(namaInstansi);
        textCell.addElement(alamatInstansi);

        headerTable.addCell(textCell);

        // ===== ADD HEADER =====
        document.add(headerTable);

        // ===== GARIS PEMBATAS =====
        LineSeparator line = new LineSeparator();
        line.setLineWidth(1);
        line.setLineColor(BaseColor.BLACK);
        document.add(new Paragraph("\n"));
        document.add(line);
        document.add(new Paragraph("\n"));

        // ================== JUDUL ==================
        Paragraph judul = new Paragraph(
                "DATA LAYANAN INTERNET",
                new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD)
        );
        judul.setAlignment(Element.ALIGN_CENTER);
        document.add(judul);
        document.add(new Paragraph("\n"));

        // ================== TABEL ==================
        // 8 kolom
        PdfPTable table = new PdfPTable(8);
        table.getDefaultCell().setBorder(Rectangle.BOTTOM);

        Font smallFont = new Font(Font.FontFamily.TIMES_ROMAN, 8, Font.NORMAL);

        String[] kolom = {
                "ID",
                "Nama Layanan",
                "Keterangan",
                "Fiber",
                "Harga",
                "FUP",
                "Bandwidth",
                "Layanan Tambahan"
        };

        for (String column : kolom) {
            PdfPCell cell = new PdfPCell(new Phrase(column, smallFont));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBorder(Rectangle.BOX);
            table.addCell(cell);
        }

        while (rs.next()) {
            String idVal = rs.getString("no_id");
            if (idVal == null || idVal.trim().isEmpty()) idVal = "-";
            PdfPCell cellId = new PdfPCell(new Phrase(idVal, smallFont));
            cellId.setBorder(Rectangle.BOX);
            cellId.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellId);

            String namaVal = rs.getString("nama_layanan");
            if (namaVal == null || namaVal.trim().isEmpty()) namaVal = "-";
            PdfPCell cellNama = new PdfPCell(new Phrase(namaVal, smallFont));
            cellNama.setBorder(Rectangle.BOX);
            table.addCell(cellNama);

            String ketVal = rs.getString("keterangan");
            if (ketVal == null || ketVal.trim().isEmpty()) ketVal = "-";
            PdfPCell cellKet = new PdfPCell(new Phrase(ketVal, smallFont));
            cellKet.setBorder(Rectangle.BOX);
            table.addCell(cellKet);

            String fiberVal = rs.getString("fiber");
            if (fiberVal == null || fiberVal.trim().isEmpty()) fiberVal = "-";
            PdfPCell cellFiber = new PdfPCell(new Phrase(fiberVal, smallFont));
            cellFiber.setBorder(Rectangle.BOX);
            cellFiber.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellFiber);

            String hargaVal = rs.getString("harga");
            if (hargaVal == null || hargaVal.trim().isEmpty()) hargaVal = "-";
            PdfPCell cellHarga = new PdfPCell(new Phrase(hargaVal, smallFont));
            cellHarga.setBorder(Rectangle.BOX);
            cellHarga.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellHarga);

            String fupVal = rs.getString("fup");
            if (fupVal == null || fupVal.trim().isEmpty()) fupVal = "-";
            PdfPCell cellFUP = new PdfPCell(new Phrase(fupVal, smallFont));
            cellFUP.setBorder(Rectangle.BOX);
            cellFUP.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellFUP);

            String bwVal = rs.getString("bandwidth");
            if (bwVal == null || bwVal.trim().isEmpty()) bwVal = "-";
            PdfPCell cellBW = new PdfPCell(new Phrase(bwVal, smallFont));
            cellBW.setBorder(Rectangle.BOX);
            cellBW.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cellBW);

            String layananVal = rs.getString("layanan_tambahan");
            if (layananVal == null || layananVal.trim().isEmpty()) layananVal = "-";
            PdfPCell cellLayanan = new PdfPCell(new Phrase(layananVal, smallFont));
            cellLayanan.setBorder(Rectangle.BOX);
            table.addCell(cellLayanan);
        }

        // ✅ atur lebar kolom biar rapi
        float[] columnWidths = {1.0f, 2.6f, 3.2f, 1.3f, 1.8f, 1.1f, 1.4f, 3.8f};
        table.setTotalWidth(document.getPageSize().getWidth() - document.leftMargin() - document.rightMargin());
        seeTableLockedWidthSafe(table, columnWidths); // helper di bawah (biar aman kalau error)

        document.add(table);

        // ================== TTD ==================
        DateTimeFormatter dateFormatter =
                DateTimeFormatter.ofPattern("EEEE, dd MMMM yyyy", new Locale("id", "ID"));
        String currentDate = LocalDate.now().format(dateFormatter);

        String formattedDate = LOKASI_TTD + ", " + currentDate;

        Font fontTanggal = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.ITALIC);
        Paragraph dateTimeParagraph = new Paragraph(formattedDate, fontTanggal);
        dateTimeParagraph.setAlignment(Element.ALIGN_RIGHT);
        dateTimeParagraph.setSpacingBefore(20);
        document.add(dateTimeParagraph);

        Paragraph jabatan = new Paragraph(JABATAN_TTD, new Font(Font.FontFamily.TIMES_ROMAN, 12));
        jabatan.setAlignment(Element.ALIGN_RIGHT);
        document.add(jabatan);

        document.add(new Paragraph("\n\n\n\n"));

        Paragraph namaPejabat = new Paragraph(NAMA_TTD, new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD));
        namaPejabat.setAlignment(Element.ALIGN_RIGHT);
        document.add(namaPejabat);

        // ================== SELESAI ==================
        document.close();

        final String finalFileName = fileName;

        SwingUtilities.invokeLater(() -> {
            JPanel loadingPanel = new JPanel();
            JProgressBar progressBar = new JProgressBar();
            progressBar.setIndeterminate(true);
            loadingPanel.add(progressBar);

            JOptionPane optionPane = new JOptionPane(
                    loadingPanel,
                    JOptionPane.INFORMATION_MESSAGE,
                    JOptionPane.DEFAULT_OPTION,
                    null,
                    new Object[]{},
                    null
            );
            JDialog dialog = optionPane.createDialog("Generate Laporan Data Layanan Internet");

            Timer timer = new Timer(2000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    dialog.dispose();
                    JOptionPane.showMessageDialog(null, "Data berhasil digenerate. Tekan OK untuk membuka file.");
                    try {
                        File file = new File(finalFileName);
                        Desktop.getDesktop().open(file);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            });
            timer.setRepeats(false);
            timer.start();

            dialog.setVisible(true);
        });

    } catch (SQLException | DocumentException | IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Gagal generate PDF: " + ex.getMessage());
    }
}

/**
 * Helper biar setWidths() aman (kadang error kalau ukuran tidak cocok).
 */
private void seeTableLockedWidthSafe(PdfPTable table, float[] widths) {
    try {
        table.setLockedWidth(true);
        table.setWidths(widths);
    } catch (Exception e) {
        // fallback: biarkan default width
        e.printStackTrace();
    }
}



    private void laporanCalonPelamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanCalonPelamarMouseClicked
generatePDFLaporanLayananInternet();
    }//GEN-LAST:event_laporanCalonPelamarMouseClicked

    private void kriteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseExited
        // TODO add your handling code here:
        kriteria.setBackground(hoverButton);
    }//GEN-LAST:event_kriteriaMouseExited

    private void kriteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseEntered
        // TODO add your handling code here:
        kriteria.setBackground(new Color(51,51,51));
        kriteria.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_kriteriaMouseEntered

    private void kriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kriteriaMouseClicked
        // TODO add your handling code here:
        showSubMenu(slideMenuPengaturan);
    }//GEN-LAST:event_kriteriaMouseClicked

    private void calonPelamarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calonPelamarMouseExited
        // TODO add your handling code here:
        calonPelamar.setBackground(hoverButton);
    }//GEN-LAST:event_calonPelamarMouseExited

    private void calonPelamarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calonPelamarMouseEntered
        // TODO add your handling code here:
        calonPelamar.setBackground(new Color(51,51,51));
        calonPelamar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_calonPelamarMouseEntered

    private void calonPelamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calonPelamarMouseClicked
        // TODO add your handling code here:
        //remove panel
        Pane.removeAll();
        Pane.repaint();
        Pane.revalidate();

        //add Panel, add panel 
        Pane.add(new DataLayananInternet());
        Pane.repaint();
        Pane.revalidate();
    }//GEN-LAST:event_calonPelamarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Pane;
    private javax.swing.JLabel calonPelamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel kriteria;
    private javax.swing.JLabel laporan;
    private javax.swing.JLabel laporanCalonPelamar;
    private javax.swing.JLabel laporanHasilSeleksi;
    private javax.swing.JLabel laporanPrioritasKriteria;
    private javax.swing.JLabel laporanPrioritasSubKriteria;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel menuPengaturanKriteria;
    private javax.swing.JLabel menuPengaturanSubKriteria;
    private javax.swing.JLabel seleksi;
    private javax.swing.JPanel slideMenuLaporan;
    private javax.swing.JPanel slideMenuPengaturan;
    // End of variables declaration//GEN-END:variables
}
